%%% Moves list
% move(name, type, power, pp, damage)
move('pound', normal, 40, 35, physical).
move('karate-chop', fighting, 50, 25, physical).
move('doubleslap', normal, 15, 10, physical).
move('comet-punch', normal, 18, 15, physical).
move('mega-punch', normal, 80, 20, physical).
move('pay-day', normal, 40, 20, physical).
move('fire-punch', fire, 75, 15, physical).
move('ice-punch', ice, 75, 15, physical).
move('thunderpunch', electric, 75, 15, physical).
move('scratch', normal, 40, 35, physical).
move('vicegrip', normal, 55, 30, physical).
move('guillotine', normal, 1, 5, physical).
move('razor-wind', normal, 80, 10, special).
move('swords-dance', normal, 0, 30, none).
move('cut', normal, 50, 30, physical).
move('gust', flying, 40, 35, special).
move('wing-attack', flying, 60, 35, physical).
move('whirlwind', normal, 0, 20, none).
move('fly', flying, 90, 15, physical).
move('bind', normal, 15, 20, physical).
move('slam', normal, 80, 20, physical).
move('vine-whip', grass, 35, 15, physical).
move('stomp', normal, 65, 20, physical).
move('double-kick', fighting, 30, 30, physical).
move('mega-kick', normal, 120, 5, physical).
move('jump-kick', fighting, 100, 10, physical).
move('rolling-kick', fighting, 60, 15, physical).
move('sand-attack', ground, 0, 15, none).
move('headbutt', normal, 70, 15, physical).
move('horn-attack', normal, 65, 25, physical).
move('fury-attack', normal, 15, 20, physical).
move('horn-drill', normal, 1, 5, physical).
move('tackle', normal, 50, 35, physical).
move('body-slam', normal, 85, 15, physical).
move('wrap', normal, 15, 20, physical).
move('take-down', normal, 90, 20, physical).
move('thrash', normal, 120, 10, physical).
move('double-edge', normal, 120, 15, physical).
move('tail-whip', normal, 0, 30, none).
move('poison-sting', poison, 15, 35, physical).
move('twineedle', bug, 25, 20, physical).
move('pin-missile', bug, 14, 20, physical).
move('leer', normal, 0, 30, none).
move('bite', dark, 60, 25, physical).
move('growl', normal, 0, 40, none).
move('roar', normal, 0, 20, none).
move('sing', normal, 0, 15, none).
move('supersonic', normal, 0, 20, none).
move('sonicboom', normal, 1, 20, special).
move('disable', normal, 0, 20, none).
move('acid', poison, 40, 30, special).
move('ember', fire, 40, 25, special).
move('flamethrower', fire, 95, 15, special).
move('mist', ice, 0, 30, none).
move('water-gun', water, 40, 25, special).
move('hydro-pump', water, 120, 5, special).
move('surf', water, 95, 15, special).
move('ice-beam', ice, 95, 10, special).
move('blizzard', ice, 120, 5, special).
move('psybeam', psychic, 65, 20, special).
move('bubblebeam', water, 65, 20, special).
move('aurora-beam', ice, 65, 20, special).
move('hyper-beam', normal, 150, 5, special).
move('peck', flying, 35, 35, physical).
move('drill-peck', flying, 80, 20, physical).
move('submission', fighting, 80, 25, physical).
move('low-kick', fighting, 1, 20, physical).
move('counter', fighting, 1, 20, physical).
move('seismic-toss', fighting, 1, 20, physical).
move('strength', normal, 80, 15, physical).
move('absorb', grass, 20, 25, special).
move('mega-drain', grass, 40, 15, special).
move('leech-seed', grass, 0, 10, none).
move('growth', normal, 0, 40, none).
move('razor-leaf', grass, 55, 25, physical).
move('solarbeam', grass, 120, 10, special).
move('poisonpowder', poison, 0, 35, none).
move('stun-spore', grass, 0, 30, none).
move('sleep-powder', grass, 0, 15, none).
move('petal-dance', grass, 120, 10, special).
move('string-shot', bug, 0, 40, none).
move('dragon-rage', dragon, 1, 10, special).
move('fire-spin', fire, 35, 15, special).
move('thundershock', electric, 40, 30, special).
move('thunderbolt', electric, 95, 15, special).
move('thunder-wave', electric, 0, 20, none).
move('thunder', electric, 120, 10, special).
move('rock-throw', rock, 50, 15, physical).
move('earthquake', ground, 100, 10, physical).
move('fissure', ground, 1, 5, physical).
move('dig', ground, 80, 10, physical).
move('toxic', poison, 0, 10, none).
move('confusion', psychic, 50, 25, special).
move('psychic', psychic, 90, 10, special).
move('hypnosis', psychic, 0, 20, none).
move('meditate', psychic, 0, 40, none).
move('agility', psychic, 0, 30, none).
move('quick-attack', normal, 40, 30, physical).
move('rage', normal, 20, 20, physical).
move('teleport', psychic, 0, 20, none).
move('night-shade', ghost, 1, 15, special).
move('mimic', normal, 0, 10, none).
move('screech', normal, 0, 40, none).
move('double-team', normal, 0, 15, none).
move('recover', normal, 0, 10, none).
move('harden', normal, 0, 30, none).
move('minimize', normal, 0, 20, none).
move('smokescreen', normal, 0, 20, none).
move('confuse-ray', ghost, 0, 10, none).
move('withdraw', water, 0, 40, none).
move('defense-curl', normal, 0, 40, none).
move('barrier', psychic, 0, 30, none).
move('light-screen', psychic, 0, 30, none).
move('haze', ice, 0, 30, none).
move('reflect', psychic, 0, 20, none).
move('focus-energy', normal, 0, 30, none).
move('bide', normal, 1, 10, physical).
move('metronome', normal, 0, 10, none).
move('mirror-move', flying, 0, 20, none).
move('selfdestruct', normal, 200, 5, physical).
move('egg-bomb', normal, 100, 10, physical).
move('lick', ghost, 20, 30, physical).
move('smog', poison, 20, 20, special).
move('sludge', poison, 65, 20, special).
move('bone-club', ground, 65, 20, physical).
move('fire-blast', fire, 120, 5, special).
move('waterfall', water, 80, 15, physical).
move('clamp', water, 35, 15, physical).
move('swift', normal, 60, 20, special).
move('skull-bash', normal, 100, 15, physical).
move('spike-cannon', normal, 20, 15, physical).
move('constrict', normal, 10, 35, physical).
move('amnesia', psychic, 0, 20, none).
move('kinesis', psychic, 0, 15, none).
move('softboiled', normal, 0, 10, none).
move('hi-jump-kick', fighting, 130, 10, physical).
move('glare', normal, 0, 30, none).
move('dream-eater', psychic, 100, 15, special).
move('poison-gas', poison, 0, 40, none).
move('barrage', normal, 15, 20, physical).
move('leech-life', bug, 20, 15, physical).
move('lovely-kiss', normal, 0, 10, none).
move('sky-attack', flying, 140, 5, physical).
move('transform', normal, 0, 10, none).
move('bubble', water, 20, 30, special).
move('dizzy-punch', normal, 70, 10, physical).
move('spore', grass, 0, 15, none).
move('flash', normal, 0, 20, none).
move('psywave', psychic, 1, 15, special).
move('splash', normal, 0, 40, none).
move('acid-armor', poison, 0, 40, none).
move('crabhammer', water, 90, 10, physical).
move('explosion', normal, 250, 5, physical).
move('fury-swipes', normal, 18, 15, physical).
move('bonemerang', ground, 50, 10, physical).
move('rest', psychic, 0, 10, none).
move('rock-slide', rock, 75, 10, physical).
move('hyper-fang', normal, 80, 15, physical).
move('sharpen', normal, 0, 30, none).
move('conversion', normal, 0, 30, none).
move('tri-attack', normal, 80, 10, special).
move('super-fang', normal, 1, 10, physical).
move('slash', normal, 70, 20, physical).
move('substitute', normal, 0, 10, none).
move('struggle', normal, 50, inf, physical).
move('sketch', normal, 0, 1, none).
move('triple-kick', fighting, 10, 10, physical).
move('thief', dark, 40, 10, physical).
move('spider-web', bug, 0, 10, none).
move('mind-reader', normal, 0, 5, none).
move('nightmare', ghost, 0, 15, none).
move('flame-wheel', fire, 60, 25, physical).
move('snore', normal, 40, 15, special).
move('curse', ghost, 0, 10, none).
move('flail', normal, 1, 15, physical).
move('conversion-2', normal, 0, 30, none).
move('aeroblast', flying, 100, 5, special).
move('cotton-spore', grass, 0, 40, none).
move('reversal', fighting, 1, 15, physical).
move('spite', ghost, 0, 10, none).
move('powder-snow', ice, 40, 25, special).
move('protect', normal, 0, 10, none).
move('mach-punch', fighting, 40, 30, physical).
move('scary-face', normal, 0, 10, none).
move('faint-attack', dark, 60, 20, physical).
move('sweet-kiss', normal, 0, 10, none).
move('belly-drum', normal, 0, 10, none).
move('sludge-bomb', poison, 90, 10, special).
move('mud-slap', ground, 20, 10, special).
move('octazooka', water, 65, 10, special).
move('spikes', ground, 0, 20, none).
move('zap-cannon', electric, 120, 5, special).
move('foresight', normal, 0, 40, none).
move('destiny-bond', ghost, 0, 5, none).
move('perish-song', normal, 0, 5, none).
move('icy-wind', ice, 55, 15, special).
move('detect', fighting, 0, 5, none).
move('bone-rush', ground, 25, 10, physical).
move('lock-on', normal, 0, 5, none).
move('outrage', dragon, 120, 10, physical).
move('sandstorm', rock, 0, 10, none).
move('giga-drain', grass, 75, 10, special).
move('endure', normal, 0, 10, none).
move('charm', normal, 0, 20, none).
move('rollout', rock, 30, 20, physical).
move('false-swipe', normal, 40, 40, physical).
move('swagger', normal, 0, 15, none).
move('milk-drink', normal, 0, 10, none).
move('spark', electric, 65, 20, physical).
move('fury-cutter', bug, 20, 20, physical).
move('steel-wing', steel, 70, 25, physical).
move('mean-look', normal, 0, 5, none).
move('attract', normal, 0, 15, none).
move('sleep-talk', normal, 0, 10, none).
move('heal-bell', normal, 0, 5, none).
move('return', normal, 1, 20, physical).
move('present', normal, 1, 15, physical).
move('frustration', normal, 1, 20, physical).
move('safeguard', normal, 0, 25, none).
move('pain-split', normal, 0, 20, none).
move('sacred-fire', fire, 100, 5, physical).
move('magnitude', ground, 1, 30, physical).
move('dynamicpunch', fighting, 100, 5, physical).
move('megahorn', bug, 120, 10, physical).
move('dragonbreath', dragon, 60, 20, special).
move('baton-pass', normal, 0, 40, none).
move('encore', normal, 0, 5, none).
move('pursuit', dark, 40, 20, physical).
move('rapid-spin', normal, 20, 40, physical).
move('sweet-scent', normal, 0, 20, none).
move('iron-tail', steel, 100, 15, physical).
move('metal-claw', steel, 50, 35, physical).
move('vital-throw', fighting, 70, 10, physical).
move('morning-sun', normal, 0, 5, none).
move('synthesis', grass, 0, 5, none).
move('moonlight', normal, 0, 5, none).
move('hidden-power', normal, 1, 15, special).
move('cross-chop', fighting, 100, 5, physical).
move('twister', dragon, 40, 20, special).
move('rain-dance', water, 0, 5, none).
move('sunny-day', fire, 0, 5, none).
move('crunch', dark, 80, 15, physical).
move('mirror-coat', psychic, 1, 20, special).
move('psych-up', normal, 0, 10, none).
move('extremespeed', normal, 80, 5, physical).
move('ancientpower', rock, 60, 5, special).
move('shadow-ball', ghost, 80, 15, special).
move('future-sight', psychic, 100, 10, special).
move('rock-smash', fighting, 40, 15, physical).
move('whirlpool', water, 35, 15, special).
move('beat-up', dark, 1, 10, physical).
move('fake-out', normal, 40, 10, physical).
move('uproar', normal, 90, 10, special).
move('stockpile', normal, 0, 20, none).
move('spit-up', normal, 1, 10, special).
move('swallow', normal, 0, 10, none).
move('heat-wave', fire, 100, 10, special).
move('hail', ice, 0, 10, none).
move('torment', dark, 0, 15, none).
move('flatter', dark, 0, 15, none).
move('will-o-wisp', fire, 0, 15, none).
move('memento', dark, 0, 10, none).
move('facade', normal, 70, 20, physical).
move('focus-punch', fighting, 150, 20, physical).
move('smellingsalt', normal, 60, 10, physical).
move('follow-me', normal, 0, 20, none).
move('nature-power', normal, 0, 20, none).
move('charge', electric, 0, 20, none).
move('taunt', dark, 0, 20, none).
move('helping-hand', normal, 0, 20, none).
move('trick', psychic, 0, 10, none).
move('role-play', psychic, 0, 10, none).
move('wish', normal, 0, 10, none).
move('assist', normal, 0, 20, none).
move('ingrain', grass, 0, 20, none).
move('superpower', fighting, 120, 5, physical).
move('magic-coat', psychic, 0, 15, none).
move('recycle', normal, 0, 10, none).
move('revenge', fighting, 60, 10, physical).
move('brick-break', fighting, 75, 15, physical).
move('yawn', normal, 0, 10, none).
move('knock-off', dark, 20, 20, physical).
move('endeavor', normal, 1, 5, physical).
move('eruption', fire, 150, 5, special).
move('skill-swap', psychic, 0, 10, none).
move('imprison', psychic, 0, 10, none).
move('refresh', normal, 0, 20, none).
move('grudge', ghost, 0, 5, none).
move('snatch', dark, 0, 10, none).
move('secret-power', normal, 70, 20, physical).
move('dive', water, 80, 10, physical).
move('arm-thrust', fighting, 15, 20, physical).
move('camouflage', normal, 0, 20, none).
move('tail-glow', bug, 0, 20, none).
move('luster-purge', psychic, 70, 5, special).
move('mist-ball', psychic, 70, 5, special).
move('featherdance', flying, 0, 15, none).
move('teeter-dance', normal, 0, 20, none).
move('blaze-kick', fire, 85, 10, physical).
move('mud-sport', ground, 0, 15, none).
move('ice-ball', ice, 30, 20, physical).
move('needle-arm', grass, 60, 15, physical).
move('slack-off', normal, 0, 10, none).
move('hyper-voice', normal, 90, 10, special).
move('poison-fang', poison, 50, 15, physical).
move('crush-claw', normal, 75, 10, physical).
move('blast-burn', fire, 150, 5, special).
move('hydro-cannon', water, 150, 5, special).
move('meteor-mash', steel, 100, 10, physical).
move('astonish', ghost, 30, 15, physical).
move('weather-ball', normal, 50, 10, special).
move('aromatherapy', grass, 0, 5, none).
move('fake-tears', dark, 0, 20, none).
move('air-cutter', flying, 55, 25, special).
move('overheat', fire, 140, 5, special).
move('odor-sleuth', normal, 0, 40, none).
move('rock-tomb', rock, 50, 10, physical).
move('silver-wind', bug, 60, 5, special).
move('metal-sound', steel, 0, 40, none).
move('grasswhistle', grass, 0, 15, none).
move('tickle', normal, 0, 20, none).
move('cosmic-power', psychic, 0, 20, none).
move('water-spout', water, 150, 5, special).
move('signal-beam', bug, 75, 15, special).
move('shadow-punch', ghost, 60, 20, physical).
move('extrasensory', psychic, 80, 30, special).
move('sky-uppercut', fighting, 85, 15, physical).
move('sand-tomb', ground, 35, 15, physical).
move('sheer-cold', ice, 1, 5, special).
move('muddy-water', water, 95, 10, special).
move('bullet-seed', grass, 25, 30, physical).
move('aerial-ace', flying, 60, 20, physical).
move('icicle-spear', ice, 25, 30, physical).
move('iron-defense', steel, 0, 15, none).
move('block', normal, 0, 5, none).
move('howl', normal, 0, 40, none).
move('dragon-claw', dragon, 80, 15, physical).
move('frenzy-plant', grass, 150, 5, special).
move('bulk-up', fighting, 0, 20, none).
move('bounce', flying, 85, 5, physical).
move('mud-shot', ground, 55, 15, special).
move('poison-tail', poison, 50, 25, physical).
move('covet', normal, 60, 40, physical).
move('volt-tackle', electric, 120, 15, physical).
move('magical-leaf', grass, 60, 20, special).
move('water-sport', water, 0, 15, none).
move('calm-mind', psychic, 0, 20, none).
move('leaf-blade', grass, 90, 15, physical).
move('dragon-dance', dragon, 0, 20, none).
move('rock-blast', rock, 25, 10, physical).
move('shock-wave', electric, 60, 20, special).
move('water-pulse', water, 60, 20, special).
move('doom-desire', steel, 140, 5, special).
move('psycho-boost', psychic, 140, 5, special).
move('roost', flying, 0, 10, none).
move('gravity', psychic, 0, 5, none).
move('miracle-eye', psychic, 0, 40, none).
move('wake-up-slap', fighting, 60, 10, physical).
move('hammer-arm', fighting, 100, 10, physical).
move('gyro-ball', steel, 1, 5, physical).
move('healing-wish', psychic, 0, 10, none).
move('brine', water, 65, 10, special).
move('natural-gift', normal, 1, 15, physical).
move('feint', normal, 30, 10, physical).
move('pluck', flying, 60, 20, physical).
move('tailwind', flying, 0, 30, none).
move('acupressure', normal, 0, 30, none).
move('metal-burst', steel, 1, 10, physical).
move('u-turn', bug, 70, 20, physical).
move('close-combat', fighting, 120, 5, physical).
move('payback', dark, 50, 10, physical).
move('assurance', dark, 50, 10, physical).
move('embargo', dark, 0, 15, none).
move('fling', dark, 1, 10, physical).
move('psycho-shift', psychic, 0, 10, none).
move('trump-card', normal, 1, 5, special).
move('heal-block', psychic, 0, 15, none).
move('wring-out', normal, 1, 5, special).
move('power-trick', psychic, 0, 10, none).
move('gastro-acid', poison, 0, 10, none).
move('lucky-chant', normal, 0, 30, none).
move('me-first', normal, 1, 20, none).
move('copycat', normal, 0, 20, none).
move('power-swap', psychic, 0, 10, none).
move('guard-swap', psychic, 0, 10, none).
move('punishment', dark, 1, 5, physical).
move('last-resort', normal, 140, 5, physical).
move('worry-seed', grass, 0, 10, none).
move('sucker-punch', dark, 80, 5, physical).
move('toxic-spikes', poison, 0, 20, none).
move('heart-swap', psychic, 0, 10, none).
move('aqua-ring', water, 0, 20, none).
move('magnet-rise', electric, 0, 10, none).
move('flare-blitz', fire, 120, 15, physical).
move('force-palm', fighting, 60, 10, physical).
move('aura-sphere', fighting, 90, 20, special).
move('rock-polish', rock, 0, 20, none).
move('poison-jab', poison, 80, 20, physical).
move('dark-pulse', dark, 80, 15, special).
move('night-slash', dark, 70, 15, physical).
move('aqua-tail', water, 90, 10, physical).
move('seed-bomb', grass, 80, 15, physical).
move('air-slash', flying, 75, 20, special).
move('x-scissor', bug, 80, 15, physical).
move('bug-buzz', bug, 90, 10, special).
move('dragon-pulse', dragon, 90, 10, special).
move('dragon-rush', dragon, 100, 10, physical).
move('power-gem', rock, 70, 20, special).
move('drain-punch', fighting, 75, 10, physical).
move('vacuum-wave', fighting, 40, 30, special).
move('focus-blast', fighting, 120, 5, special).
move('energy-ball', grass, 80, 10, special).
move('brave-bird', flying, 120, 15, physical).
move('earth-power', ground, 90, 10, special).
move('switcheroo', dark, 0, 10, none).
move('giga-impact', normal, 150, 5, physical).
move('nasty-plot', dark, 0, 20, none).
move('bullet-punch', steel, 40, 30, physical).
move('avalanche', ice, 60, 10, physical).
move('ice-shard', ice, 40, 30, physical).
move('shadow-claw', ghost, 70, 15, physical).
move('thunder-fang', electric, 65, 15, physical).
move('ice-fang', ice, 65, 15, physical).
move('fire-fang', fire, 65, 15, physical).
move('shadow-sneak', ghost, 40, 30, physical).
move('mud-bomb', ground, 65, 10, special).
move('psycho-cut', psychic, 70, 20, physical).
move('zen-headbutt', psychic, 80, 15, physical).
move('mirror-shot', steel, 65, 10, special).
move('flash-cannon', steel, 80, 10, special).
move('rock-climb', normal, 90, 20, physical).
move('defog', flying, 0, 15, none).
move('trick-room', psychic, 0, 5, none).
move('draco-meteor', dragon, 140, 5, special).
move('discharge', electric, 80, 15, special).
move('lava-plume', fire, 80, 15, special).
move('leaf-storm', grass, 140, 5, special).
move('power-whip', grass, 120, 10, physical).
move('rock-wrecker', rock, 150, 5, physical).
move('cross-poison', poison, 70, 20, physical).
move('gunk-shot', poison, 120, 5, physical).
move('iron-head', steel, 80, 15, physical).
move('magnet-bomb', steel, 60, 20, physical).
move('stone-edge', rock, 100, 5, physical).
move('captivate', normal, 0, 20, none).
move('stealth-rock', rock, 0, 20, none).
move('grass-knot', grass, 1, 20, special).
move('chatter', flying, 60, 20, special).
move('judgment', normal, 100, 10, special).
move('bug-bite', bug, 60, 20, physical).
move('charge-beam', electric, 50, 10, special).
move('wood-hammer', grass, 120, 15, physical).
move('aqua-jet', water, 40, 20, physical).
move('attack-order', bug, 90, 15, physical).
move('defend-order', bug, 0, 10, none).
move('heal-order', bug, 0, 10, none).
move('head-smash', rock, 150, 5, physical).
move('double-hit', normal, 35, 10, physical).
move('roar-of-time', dragon, 150, 5, special).
move('spacial-rend', dragon, 100, 5, special).
move('lunar-dance', psychic, 0, 10, none).
move('crush-grip', normal, 1, 5, physical).
move('magma-storm', fire, 120, 5, special).
move('dark-void', dark, 0, 10, none).
move('seed-flare', grass, 120, 5, special).
move('ominous-wind', ghost, 60, 5, special).
move('shadow-force', ghost, 120, 5, physical).
move('hone-claws', dark, 0, 15, none).
move('wide-guard', rock, 0, 10, none).
move('guard-split', psychic, 0, 10, none).
move('power-split', psychic, 0, 10, none).
move('wonder-room', psychic, 0, 10, none).
move('psyshock', psychic, 80, 10, special).
move('venoshock', poison, 65, 10, special).
move('autotomize', steel, 0, 15, none).
move('rage-powder', bug, 0, 20, none).
move('telekinesis', psychic, 0, 15, none).
move('magic-room', psychic, 0, 10, none).
move('smack-down', rock, 50, 15, physical).
move('storm-throw', fighting, 40, 10, physical).
move('flame-burst', fire, 70, 15, special).
move('sludge-wave', poison, 95, 10, special).
move('quiver-dance', bug, 0, 20, none).
move('heavy-slam', steel, 1, 10, physical).
move('synchronoise', psychic, 70, 15, special).
move('electro-ball', electric, 1, 10, special).
move('soak', water, 0, 20, none).
move('flame-charge', fire, 50, 20, physical).
move('coil', poison, 0, 20, none).
move('low-sweep', fighting, 60, 20, physical).
move('acid-spray', poison, 40, 20, special).
move('foul-play', dark, 95, 15, physical).
move('simple-beam', normal, 0, 15, none).
move('entrainment', normal, 0, 15, none).
move('after-you', normal, 0, 15, none).
move('round', normal, 60, 15, special).
move('echoed-voice', normal, 40, 15, special).
move('chip-away', normal, 70, 20, physical).
move('clear-smog', poison, 50, 15, special).
move('stored-power', psychic, 20, 10, special).
move('quick-guard', fighting, 0, 15, none).
move('ally-switch', psychic, 0, 15, none).
move('scald', water, 80, 15, special).
move('shell-smash', normal, 0, 15, none).
move('heal-pulse', psychic, 0, 10, none).
move('hex', ghost, 50, 10, special).
move('sky-drop', flying, 60, 10, physical).
move('shift-gear', steel, 0, 10, none).
move('circle-throw', fighting, 60, 10, physical).
move('incinerate', fire, 30, 15, special).
move('quash', dark, 0, 15, none).
move('acrobatics', flying, 55, 15, physical).
move('reflect-type', normal, 0, 15, none).
move('retaliate', normal, 70, 5, physical).
move('final-gambit', fighting, 1, 5, special).
move('bestow', normal, 0, 15, none).
move('inferno', fire, 100, 5, special).
move('water-pledge', water, 50, 10, special).
move('fire-pledge', fire, 50, 10, special).
move('grass-pledge', grass, 50, 10, special).
move('volt-switch', electric, 70, 20, special).
move('struggle-bug', bug, 30, 20, special).
move('bulldoze', ground, 60, 20, physical).
move('frost-breath', ice, 40, 10, special).
move('dragon-tail', dragon, 60, 10, physical).
move('work-up', normal, 0, 30, none).
move('electroweb', electric, 55, 15, special).
move('wild-charge', electric, 90, 15, physical).
move('drill-run', ground, 80, 10, physical).
move('dual-chop', dragon, 40, 15, physical).
move('heart-stamp', psychic, 60, 25, physical).
move('horn-leech', grass, 75, 10, physical).
move('sacred-sword', fighting, 90, 20, physical).
move('razor-shell', water, 75, 10, physical).
move('heat-crash', fire, 1, 10, physical).
move('leaf-tornado', grass, 65, 10, special).
move('steamroller', bug, 65, 20, physical).
move('cotton-guard', grass, 0, 10, none).
move('night-daze', dark, 85, 10, special).
move('psystrike', psychic, 100, 10, special).
move('tail-slap', normal, 25, 10, physical).
move('hurricane', flying, 120, 10, special).
move('head-charge', normal, 120, 15, physical).
move('gear-grind', steel, 50, 15, physical).
move('searing-shot', fire, 100, 5, special).
move('techno-blast', normal, 85, 5, special).
move('relic-song', normal, 75, 10, special).
move('secret-sword', fighting, 85, 10, special).
move('glaciate', ice, 65, 10, special).
move('bolt-strike', electric, 130, 5, physical).
move('blue-flare', fire, 130, 5, special).
move('fiery-dance', fire, 80, 10, special).
move('freeze-shock', ice, 140, 5, physical).
move('ice-burn', ice, 140, 5, special).
move('snarl', dark, 55, 15, special).
move('icicle-crash', ice, 85, 10, physical).
move('v-create', fire, 180, 5, physical).
move('fusion-flare', fire, 100, 5, special).
move('fusion-bolt', electric, 100, 5, physical).
